[versions]
espresso = "3.7.0"
gradle = "9.0.1"
hilt = "2.59.1"
kotlin = "2.3.20"
coroutines = "1.10.2"
ksp = "2.3.5"
paging = "3.4.1"
room = "2.8.4"
vcard4android = "03a37a8"
detekt = "1.23.8"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
preference = { group = "androidx.preference", name = "preference-ktx", version = "1.2.1" }
activity = { group = "androidx.activity", name = "activity-ktx", version = "1.12.4" }
core = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }

test-core = { module = "androidx.test:core", version = "1.7.0" }
test-runner = { module = "androidx.test:runner", version = "1.7.0" }
test-rules = { module = "androidx.test:rules", version = "1.7.0" }

espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }

libphonenumber = { module = "io.michaelrocks:libphonenumber-android", version = "9.0.24" }
junit = { module = "junit:junit", version = "4.13.2" }
truth = { module = "com.google.truth:truth", version = "1.4.5" }
mockito = { module = "org.mockito.kotlin:mockito-kotlin", version = "6.2.3" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

robolectric = { module = "org.robolectric:robolectric", version = "4.16.1" }
material = { module = "com.google.android.material:material", version = "1.13.0" }
vcard4android = { module = "com.github.bitfireAT:vcard4android", version.ref = "vcard4android" }
desugarjdklibs = { module = "com.android.tools:desugar_jdk_libs", version = "2.1.5" }

room-kotlin = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[bundles]
test = ["test-core", "test-runner", "test-rules"]
espresso = ["espresso-core", "espresso-intents", "espresso-contrib"]

[plugins]
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }